### ISSUE TITLE
Dokumentace dostupných filtrů, maker a jejich použití

### ISSUE THREAD

**Issue by enzy** [manGoweb/MangoPressTemplating#6]
Když ne ručně, tak alespoň generovanou PHPDoc někam, ať se to dá lehce procházet

**Comment by ViliamKopecky** [comment]
Tohle? https://github.com/manGoweb/MangoPress/wiki/Template-filters

**Comment by enzy** [comment]
closed by 0696ebd5cfab1faf38c393945e91b5e5a1259b53
